mysql:
  database: muffins_development
  user: root
  bin_log: /var/lib/mysql/binlog/mysql-bin

s3:
  bucket: db_backups
  access_key_id: XXXXXXXXXXXXXXX
  secret_access_key: XXXXXXXXXXXXXXXXXXXXXX
  