mysql:
  database: talker_development
  user: root
  bin_log: /var/lib/mysql/binlog/mysql-bin

s3:
  bucket: mysql_backups_test
  access_key_id: XXXXXXXXXXXXXXX
  secret_access_key: XXXXXXXXXXXXXXXXXXXXXX
  